/**
 * Clipboard slice — copy/cut/paste for layer subtrees.
 *
 * The clipboard is GLOBAL (not per-site): copying a node in one site can be
 * pasted into another. That makes the slice the single owner of the
 * `pb-clipboard-v1` localStorage key — every read/write goes through this
 * slice. The persisted shape is validated via TypeBox (`ClipboardPayloadSchema`)
 * on load; corruption silently resolves to "no clipboard" rather than throwing.
 *
 * Multi-root payloads (Task #multi-select):
 * - The persisted payload now stores `rootNodeIds: string[]`. A single-node
 *   copy is `[id]`; a multi-select copy preserves selection order.
 * - Paste places every root in document order under the resolved location;
 *   cross-site class import / scoped-class remapping logic is shared between
 *   roots in one transaction.
 *
 * Paste placement is "smart": if the right-clicked target accepts children,
 * the subtree is pasted as the last child of the target; otherwise it is
 * pasted as the next sibling under the target's parent. The page root is
 * always treated as a container.
 *
 * Cross-site paste rules:
 * - Framework classes (`framework:*`) are matched by NAME against the target
 *   site's class registry; if no match exists, the classId is dropped.
 *   Framework classes are deterministically generated by the target site, so
 *   importing the source-side definitions would pollute the target.
 * - Scoped (module-style) classes are always cloned with a fresh ID and the
 *   `scope.nodeId` remapped to the new node ID; scopes referencing nodes
 *   outside the copied subtree are dropped.
 * - All other (regular) classes are imported into the target site preserving
 *   their original ID. Same-ID classes already in the target are reused.
 */

import { nanoid } from 'nanoid'
import type { CSSClass, Page, PageNode } from '@core/page-tree'
import {
  buildSubtreeNodeIdMap,
  getParent,
  pasteSubtree,
} from '@core/page-tree'
import { registry } from '@core/module-engine/registry'
import {
  CLIPBOARD_VERSION,
  type ClipboardPayload,
  clearClipboardPayload,
  readClipboardPayload,
  writeClipboardPayload,
} from '@site/store/clipboard/clipboardStorage'
import type { EditorStoreSliceCreator } from '@site/store/types'

/**
 * In-memory snapshot of the latest copy/cut. Mirrors the persisted payload
 * but is also kept reactively on the store so menus / shortcuts can react
 * to clipboard changes without polling localStorage.
 *
 * `rootNodeIds` is ordered: a multi-select copy preserves selection order,
 * a single-node copy is a 1-length array.
 */
export interface ClipboardEntry {
  rootNodeIds: string[]
  nodes: Record<string, PageNode>
  classes: Record<string, CSSClass>
  copiedAt: number
}

export interface ClipboardSlice {
  /** Latest copied / cut subtree(s). Null when the clipboard is empty. */
  clipboardEntry: ClipboardEntry | null

  /** Capture a node's subtree into the clipboard (in memory + localStorage). */
  copyNode: (nodeId: string) => boolean
  /** Capture a multi-selection of subtrees as one ordered clipboard payload. */
  copyNodes: (nodeIds: string[]) => boolean
  /**
   * Copy a node's subtree, then delete it from the active page.
   * Returns true if a copy + delete actually happened.
   */
  cutNode: (nodeId: string) => boolean
  /** Multi-cut: copy then delete every id in one undo step. */
  cutNodes: (nodeIds: string[]) => boolean
  /**
   * Paste the clipboard subtree(s) relative to `targetNodeId`.
   * If the target accepts children, the subtree is appended inside it;
   * otherwise it's inserted as the next sibling under the target's parent.
   * For multi-root payloads, every root is placed consecutively in selection
   * order at the resolved location (single undo step).
   * Returns the new root node IDs (in selection order), or null if paste was
   * a no-op.
   */
  pasteNode: (targetNodeId: string) => string[] | null

  /** Clear the clipboard from memory + localStorage. */
  clearClipboard: () => void
}

declare module '@site/store/types' {
  // Surface this slice's fields on the combined EditorStore type.
  interface EditorStore extends ClipboardSlice {}
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Find the active Page document on the store, ignoring VC mode. */
function getActivePage(state: {
  site: { pages: Page[] } | null
  activePageId: string | null
}): Page | null {
  if (!state.site || !state.activePageId) return null
  return state.site.pages.find((p) => p.id === state.activePageId) ?? null
}

/**
 * Reduce a multi-selection to its top-level set (drop ids whose ancestor is
 * also in the selection — those would be copied with the ancestor anyway).
 *
 * Returned ids preserve input order.
 */
function topLevelOnly(page: Page, ids: string[]): string[] {
  const idSet = new Set(ids)
  const result: string[] = []
  for (const id of ids) {
    let ancestor = getParent(page, id)
    let dominated = false
    while (ancestor) {
      if (idSet.has(ancestor.id)) {
        dominated = true
        break
      }
      ancestor = getParent(page, ancestor.id)
    }
    if (!dominated) result.push(id)
  }
  return result
}

/**
 * Collect the subtrees rooted at every id in `rootIds` into a single flat
 * nodes map. Used by both single- and multi-copy code paths. Skips ids not
 * present in the page (returning a non-null payload as long as at least one
 * root resolved).
 */
function collectSubtrees(
  page: Page,
  rootIds: string[],
): { rootNodeIds: string[]; nodes: Record<string, PageNode> } | null {
  if (rootIds.length === 0) return null
  const nodes: Record<string, PageNode> = {}
  const validRoots: string[] = []
  for (const rootId of rootIds) {
    if (!page.nodes[rootId]) continue
    validRoots.push(rootId)
    const stack = [rootId]
    while (stack.length > 0) {
      const id = stack.pop()!
      if (nodes[id]) continue
      const node = page.nodes[id]
      if (!node) continue
      nodes[id] = { ...node, children: [...node.children] }
      stack.push(...node.children)
    }
  }
  if (validRoots.length === 0) return null
  return { rootNodeIds: validRoots, nodes }
}

/**
 * Collect every class referenced anywhere in the subtree from `siteClasses`.
 * Missing classes (e.g. dangling classIds) are silently skipped — the paste
 * step also filters dangling references via the classIdRemap.
 */
function collectReferencedClasses(
  nodes: Record<string, PageNode>,
  siteClasses: Record<string, CSSClass>,
): Record<string, CSSClass> {
  const classes: Record<string, CSSClass> = {}
  for (const node of Object.values(nodes)) {
    for (const classId of node.classIds) {
      if (classes[classId]) continue
      const cls = siteClasses[classId]
      if (cls) classes[classId] = cls
    }
  }
  return classes
}

/**
 * Decide where to paste relative to a target node.
 * - If `target` accepts children (or is the page root), paste inside as the last child.
 * - Otherwise, paste as the next sibling under the target's parent.
 * Returns null if the target is invalid for any reason (e.g. orphan node).
 */
function resolvePasteLocation(
  page: Page,
  targetNodeId: string,
): { parentId: string; index: number | undefined } | null {
  const target = page.nodes[targetNodeId]
  if (!target) return null

  // The page root always accepts children; module registry may or may not have
  // an entry for it depending on registration order. Treat root as a container.
  const isRoot = page.rootNodeId === targetNodeId
  const definition = registry.get(target.moduleId)
  const acceptsChildren = isRoot || definition?.canHaveChildren === true

  if (acceptsChildren) {
    return { parentId: targetNodeId, index: undefined }
  }

  const parent = getParent(page, targetNodeId)
  if (!parent) return null
  const idx = parent.children.indexOf(targetNodeId)
  return { parentId: parent.id, index: idx >= 0 ? idx + 1 : undefined }
}

const FRAMEWORK_ID_PREFIX = 'framework:'

// ---------------------------------------------------------------------------
// Slice implementation
// ---------------------------------------------------------------------------

export const createClipboardSlice: EditorStoreSliceCreator<ClipboardSlice> = (
  set,
  get,
) => {
  // Hydrate the in-memory entry from localStorage at slice creation. The
  // store is built once per session, so this runs at editor mount only.
  const persisted = readClipboardPayload()
  const initialEntry: ClipboardEntry | null = persisted
    ? {
        rootNodeIds: persisted.rootNodeIds,
        nodes: persisted.nodes,
        classes: persisted.classes,
        copiedAt: persisted.copiedAt,
      }
    : null

  function persistEntry(entry: ClipboardEntry): void {
    const payload: ClipboardPayload = {
      version: CLIPBOARD_VERSION,
      rootNodeIds: entry.rootNodeIds,
      nodes: entry.nodes,
      classes: entry.classes,
      copiedAt: entry.copiedAt,
    }
    writeClipboardPayload(payload)
  }

  /** Shared implementation for `copyNode` / `copyNodes`. */
  function copyImpl(nodeIds: string[]): boolean {
    const state = get()
    const page = getActivePage(state)
    if (!page) return false
    if (nodeIds.length === 0) return false

    // Refuse to include the page root — duplicating "the entire page body" has
    // no meaningful target placement and matches existing root-guard policy.
    const filtered = nodeIds.filter((id) => id !== page.rootNodeId)
    if (filtered.length === 0) return false

    const tops = topLevelOnly(page, filtered)
    const subtrees = collectSubtrees(page, tops)
    if (!subtrees) return false

    const siteClasses = state.site?.classes ?? {}
    const classes = collectReferencedClasses(subtrees.nodes, siteClasses)
    const entry: ClipboardEntry = {
      rootNodeIds: subtrees.rootNodeIds,
      nodes: subtrees.nodes,
      classes,
      copiedAt: Date.now(),
    }
    set({ clipboardEntry: entry })
    persistEntry(entry)
    return true
  }

  return {
    clipboardEntry: initialEntry,

    copyNode: (nodeId) => copyImpl([nodeId]),

    copyNodes: (nodeIds) => copyImpl(nodeIds),

    cutNode: (nodeId) => {
      const state = get()
      const page = getActivePage(state)
      if (!page) return false
      if (page.rootNodeId === nodeId) return false

      // Copy first; if copy fails (orphan node), don't delete.
      if (!state.copyNode(nodeId)) return false
      // Reuse the existing deleteNode action so undo history + selection
      // behave identically to a manual delete.
      get().deleteNode(nodeId)
      return true
    },

    cutNodes: (nodeIds) => {
      const state = get()
      const page = getActivePage(state)
      if (!page) return false
      if (nodeIds.length === 0) return false
      if (!state.copyNodes(nodeIds)) return false
      // Single undo step for the whole multi-cut. `deleteNodes` orders by
      // depth-DESC and skips redundant ids, matching the copy semantics.
      get().deleteNodes(nodeIds)
      return true
    },

    pasteNode: (targetNodeId) => {
      const state = get()
      const entry = state.clipboardEntry
      if (!entry || entry.rootNodeIds.length === 0) return null

      const page = getActivePage(state)
      if (!page) return null
      const location = resolvePasteLocation(page, targetNodeId)
      if (!location) return null

      // Pre-compute new node IDs across ALL roots so scoped-class scope.nodeId
      // can be remapped before classes are written into the target site.
      // Each root's subtree gets its own id-remap; we union them into one map
      // so a class scoped to any pasted node finds its remap.
      const nodeIdMap = new Map<string, string>()
      for (const rootId of entry.rootNodeIds) {
        const subtreeMap = buildSubtreeNodeIdMap(rootId, entry.nodes)
        for (const [oldId, newId] of subtreeMap) {
          if (!nodeIdMap.has(oldId)) nodeIdMap.set(oldId, newId)
        }
      }

      // Build the class plan. Each entry resolves to one of:
      //   - { kind: 'reuse', id }   — already present in target site
      //   - { kind: 'add', cls }    — write `cls` to site.classes (id may differ)
      //   - { kind: 'drop' }        — strip from pasted classIds
      type ClassPlan =
        | { kind: 'reuse'; id: string }
        | { kind: 'add'; id: string; cls: CSSClass }
        | { kind: 'drop' }

      const targetSite = state.site
      if (!targetSite) return null

      const now = Date.now()
      const targetClasses = targetSite.classes
      const plans = new Map<string, ClassPlan>()

      // Build a name → id index for framework classes in the target site (used
      // to match framework references that might have a different id across sites).
      const frameworkByName = new Map<string, string>()
      for (const [id, cls] of Object.entries(targetClasses)) {
        if (id.startsWith(FRAMEWORK_ID_PREFIX)) frameworkByName.set(cls.name, id)
      }

      for (const [classId, cls] of Object.entries(entry.classes)) {
        if (cls.scope?.type === 'node') {
          // Scoped class — always cloned with a fresh id, scope.nodeId remapped.
          const newScopeNodeId = nodeIdMap.get(cls.scope.nodeId)
          if (!newScopeNodeId) {
            plans.set(classId, { kind: 'drop' })
            continue
          }
          const newId = nanoid()
          plans.set(classId, {
            kind: 'add',
            id: newId,
            cls: {
              ...cls,
              id: newId,
              scope: { ...cls.scope, nodeId: newScopeNodeId },
              styles: { ...cls.styles },
              breakpointStyles: Object.fromEntries(
                Object.entries(cls.breakpointStyles).map(([bp, s]) => [
                  bp,
                  { ...s },
                ]),
              ),
              createdAt: now,
              updatedAt: now,
            },
          })
        } else if (classId.startsWith(FRAMEWORK_ID_PREFIX)) {
          // Framework class — reuse if id matches; else try by name; else drop.
          if (targetClasses[classId]) {
            plans.set(classId, { kind: 'reuse', id: classId })
          } else {
            const matchedId = frameworkByName.get(cls.name)
            plans.set(
              classId,
              matchedId
                ? { kind: 'reuse', id: matchedId }
                : { kind: 'drop' },
            )
          }
        } else {
          // Regular class — reuse if id is already in target, else import as-is.
          if (targetClasses[classId]) {
            plans.set(classId, { kind: 'reuse', id: classId })
          } else {
            plans.set(classId, {
              kind: 'add',
              id: classId,
              cls: {
                ...cls,
                styles: { ...cls.styles },
                breakpointStyles: Object.fromEntries(
                  Object.entries(cls.breakpointStyles).map(([bp, s]) => [
                    bp,
                    { ...s },
                  ]),
                ),
              },
            })
          }
        }
      }

      // classIdRemap: classes referenced by the subtree but not present in
      // entry.classes (e.g. payload was hand-edited) silently fall through —
      // reused if they exist in the target, dropped otherwise.
      const classIdRemap = (classId: string): string | null => {
        const plan = plans.get(classId)
        if (plan) {
          if (plan.kind === 'drop') return null
          return plan.id
        }
        return targetClasses[classId] ? classId : null
      }

      // Snapshot history once; the entire paste is a single undo step.
      get().pushHistory()
      const newRootIds: string[] = []
      set((draft) => {
        if (!draft.site) return
        const draftPage = draft.site.pages.find((p) => p.id === draft.activePageId)
        if (!draftPage) return

        // 1. Materialise added classes into the target site.
        for (const plan of plans.values()) {
          if (plan.kind === 'add' && !draft.site.classes[plan.id]) {
            draft.site.classes[plan.id] = plan.cls
          }
        }

        // 2. Insert each root's subtree at the resolved location, preserving
        //    selection order. For "inside" pastes (target accepts children),
        //    every root is appended; for "next sibling" pastes, each root
        //    increments the insertion index so siblings end up adjacent.
        let runningIndex = location.index
        for (const rootId of entry.rootNodeIds) {
          const newId = pasteSubtree(
            draftPage,
            { rootNodeId: rootId, nodes: entry.nodes },
            location.parentId,
            runningIndex,
            { nodeIdMap, classIdRemap },
          )
          newRootIds.push(newId)
          if (typeof runningIndex === 'number') runningIndex += 1
        }

        draft.site.updatedAt = Date.now()
        draft.hasUnsavedChanges = true
      })

      return newRootIds.length > 0 ? newRootIds : null
    },

    clearClipboard: () => {
      set({ clipboardEntry: null })
      clearClipboardPayload()
    },
  }
}
